@php
    $questions = [];
    foreach($test->phan as $phan) {
        foreach($phan->cauhoi as $question) {
            $questions[] = [
                'question' => $question,
                'audio' => $phan->tepamthanh ? asset('storage/' . $phan->tepamthanh->DuongDan) : '',
                'correct_option' => $question->phuongancauhoi->firstWhere('DapAn', 'Dung'),
                'options' => $question->phuongancauhoi
            ];
        }
    }
@endphp

<div id="game-workspace" class="w-full relative z-10 animate-fade-in text-slate-800">
    <div class="flex flex-col lg:flex-row gap-6 w-full items-stretch">
        
        <!-- LEFT/CENTER MAIN CONSOLE (Ocean & Controls) -->
        <div class="flex-grow flex flex-col bg-white border-4 border-amber-300 rounded-[2.5rem] shadow-[0_20px_50px_rgba(0,0,0,0.15)] overflow-hidden">
            
            <!-- TOP HUD BAR -->
            <div class="bg-gradient-to-r from-sky-400 via-sky-500 to-blue-500 text-white px-6 py-4 flex flex-wrap items-center justify-between gap-4 border-b-4 border-blue-600/20 font-bold select-none relative z-20">
                <!-- Current Level / Game Mode -->
                <div class="flex items-center gap-2">
                    <span class="bg-amber-400 text-slate-900 text-xs px-3 py-1.5 rounded-full font-black uppercase tracking-wider shadow-sm" id="game-mode-badge">
                        Word Listening
                    </span>
                    <span class="text-sm font-black tracking-wider text-sky-50" id="current-level-title">
                        Fishing For Words // Map 2: {{ $map->TenBanDo }}
                    </span>
                </div>
                <!-- Stats Indicators -->
                <div class="flex items-center gap-4 sm:gap-6">
                    <!-- Lives -->
                    <div class="flex items-center gap-1.5 bg-blue-600/30 px-3.5 py-1.5 rounded-full border border-blue-400/30 shadow-inner">
                        <span class="text-[9px] font-black tracking-wider text-sky-200 mr-0.5 uppercase">LIVES</span>
                        <div id="hearts-container" class="flex items-center gap-1">
                            <!-- Hearts generated by JS -->
                        </div>
                    </div>
                    <!-- XP -->
                    <div class="flex items-center gap-1.5 bg-blue-600/30 px-3.5 py-1.5 rounded-full border border-blue-400/30 shadow-inner">
                        <span class="text-amber-300 text-sm">⭐</span>
                        <span class="text-xs font-mono font-black" id="xp-display">0 XP</span>
                    </div>
                    <!-- Coins -->
                    <div class="flex items-center gap-1.5 bg-blue-600/30 px-3.5 py-1.5 rounded-full border border-blue-400/30 shadow-inner">
                        <span class="text-yellow-300 text-sm">🪙</span>
                        <span class="text-xs font-mono font-black" id="coins-display">0</span>
                    </div>
                    <!-- Combo -->
                    <div class="flex items-center gap-1.5 bg-orange-600/30 px-3.5 py-1.5 rounded-full border border-orange-400/30 text-orange-200 shadow-inner" id="combo-hud-wrapper">
                        <span class="text-sm">🔥</span>
                        <span class="text-xs font-mono font-black" id="combo-display">1.0x</span>
                    </div>
                </div>
            </div>

            <!-- CENTER AREA: Ocean scene -->
            <div id="ocean-scene" class="relative w-full h-[520px] overflow-hidden select-none bg-sky-200">
                <!-- Beach Background (Top 30% beach/sky, bottom 70% ocean) -->
                <div class="absolute inset-0 z-0 pointer-events-none bg-no-repeat" style="background-image: url('{{ asset('images/fishing/map2_bg.jpg') }}'); background-size: 100% 180%; background-position: center bottom;"></div>
                
                <!-- Ocean water overlay at bottom 75% of screen -->
                <div class="absolute bottom-0 inset-x-0 h-[380px] bg-gradient-to-b from-cyan-400/35 via-blue-500/40 to-blue-700/65 border-t-4 border-cyan-300/30 z-10 pointer-events-none"></div>

                <!-- Wave animations -->
                <div class="absolute bottom-[365px] left-0 right-0 h-8 bg-repeat-x z-10 pointer-events-none opacity-40 animate-wave-slow" style="background-image: url('data:image/svg+xml;utf8,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 1200 120%22 preserveAspectRatio=%22none%22><path d=%22M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,42.4V0Z%22 fill=%22%2322d3ee%22/></svg>'); background-size: 600px 32px;"></div>
                <div class="absolute bottom-[360px] left-0 right-0 h-8 bg-repeat-x z-10 pointer-events-none opacity-60 animate-wave-fast" style="background-image: url('data:image/svg+xml;utf8,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 1200 120%22 preserveAspectRatio=%22none%22><path d=%22M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,42.4V0Z%22 fill=%22%230ea5e9%22/></svg>'); background-size: 400px 32px;"></div>

                <!-- SVG layer for drawing fishing line -->
                <svg id="fishing-line-svg" class="absolute inset-0 w-full h-full pointer-events-none z-20">
                    <path id="fishing-line-path" d="" stroke="#f8fafc" stroke-width="2.5" fill="none" stroke-linecap="round" />
                </svg>

                <!-- Hook Element -->
                <div id="fishing-hook" class="absolute w-6 h-6 z-30 pointer-events-none hidden select-none flex items-center justify-center">
                    <span class="text-xl leading-none">🪝</span>
                </div>

                <!-- Fisherman character (Sitting on chair, holding rod) -->
                <div id="fisherman-character" class="absolute bottom-[230px] left-[5%] w-[150px] h-[150px] z-20 pointer-events-none">
                    <img src="{{ asset('images/fishing/map2_fisherman.png') }}" class="w-full h-full object-contain" />
                </div>

                <!-- Swimming Fish Container -->
                <div id="swimming-zone" class="absolute inset-0 z-10"></div>

                <!-- Interactive overlay messages (e.g. Floating damage texts, feedback toasts) -->
                <div id="effect-overlay" class="absolute inset-0 z-30 pointer-events-none"></div>

                <!-- GAME STATE OVERLAY SCREENS -->
                <!-- SCREEN 1: Game Launch Screen -->
                <div id="screen-launch" class="absolute inset-0 bg-slate-950/80 backdrop-blur-md z-40 flex flex-col items-center justify-center p-8 text-center select-none transition-all duration-300">
                    <div class="relative mb-6">
                        <div class="absolute inset-0 bg-blue-500/30 rounded-full blur-2xl animate-pulse"></div>
                        <div class="w-24 h-24 rounded-3xl bg-gradient-to-tr from-sky-400 to-indigo-600 flex items-center justify-center text-white text-5xl shadow-[0_0_35px_rgba(14,165,233,0.5)] border-4 border-amber-300 relative z-10">
                            ⚓
                        </div>
                    </div>
                    <h4 class="text-4xl font-extrabold text-white uppercase tracking-wider mb-2" style="font-family: 'Outfit', sans-serif;">FISHING FOR WORDS</h4>
                    <p class="text-slate-300 text-sm max-w-md mt-2 leading-relaxed mb-6">Chào mừng đến với chuyến câu cá từ vựng! Hãy nghe kỹ âm thanh phát ra và câu đúng chú cá đang mang đáp án chính xác!</p>
                    <button type="button" 
                            id="btn-game-start"
                            class="px-8 py-4 bg-gradient-to-r from-amber-400 to-orange-500 hover:from-amber-300 hover:to-orange-400 text-slate-950 font-black text-base tracking-wider rounded-2xl shadow-[0_0_25px_rgba(245,158,11,0.4)] active:scale-95 transition-all cursor-pointer border-2 border-white/20">
                        BẮT ĐẦU CÂU CÁ
                    </button>
                </div>

                <!-- SCREEN 2: Game Over Screen -->
                <div id="screen-gameover" class="absolute inset-0 bg-slate-950/90 backdrop-blur-md z-40 flex flex-col items-center justify-center p-8 text-center select-none hidden transition-all duration-300">
                    <div class="w-20 h-20 rounded-full bg-red-950/80 border-4 border-rose-500 text-rose-500 flex items-center justify-center text-4xl shadow-[0_0_25px_rgba(244,63,94,0.4)] mb-6 animate-bounce">
                        💔
                    </div>
                    <h4 class="text-3xl font-black text-rose-500 uppercase tracking-widest mb-2" style="font-family: 'Outfit', sans-serif;">HẾT LƯỢT CHƠI</h4>
                    <p class="text-slate-400 text-sm max-w-xs mt-2 leading-relaxed mb-6">Bạn đã hết số lượng mạng chơi của màn này. Đừng nản lòng, hãy nghe lại cẩn thận và thử sức lại nhé!</p>
                    <button type="button" 
                            id="btn-game-replay"
                            class="px-6 py-3.5 bg-gradient-to-r from-rose-500 to-red-600 hover:from-rose-600 hover:to-red-700 text-white font-black text-sm tracking-wider rounded-xl active:scale-95 transition-all cursor-pointer border border-white/10 shadow-lg shadow-rose-600/20">
                        <i class="fas fa-redo mr-1"></i> THỬ LẠI (REPLAY)
                    </button>
                </div>

                <!-- SCREEN 3: Level Completed Screen -->
                <div id="screen-win" class="absolute inset-0 bg-slate-950/85 backdrop-blur-md z-40 flex flex-col items-center justify-center p-8 text-center select-none hidden transition-all duration-300">
                    <div class="relative mb-6">
                        <div class="absolute inset-0 bg-emerald-500/30 rounded-full blur-2xl animate-pulse"></div>
                        <div class="w-24 h-24 rounded-full bg-gradient-to-tr from-emerald-400 to-teal-500 flex items-center justify-center text-white text-5xl shadow-[0_0_30px_rgba(16,185,129,0.5)] border-4 border-amber-300 relative z-10">
                            🏆
                        </div>
                    </div>
                    <h4 class="text-3xl font-black text-emerald-400 uppercase tracking-wider mb-2" style="font-family: 'Outfit', sans-serif;">HOÀN THÀNH THỬ THÁCH!</h4>
                    <p class="text-slate-300 text-sm max-w-sm mt-2 leading-relaxed mb-6">Xuất sắc! Bạn đã thu thập được nhiều loài cá quý và trả lời đúng tất cả các bài nghe!</p>
                    <button type="button" 
                            id="btn-submit-game"
                            class="group relative flex items-center gap-3 bg-gradient-to-r from-emerald-400 to-teal-600 hover:from-emerald-500 hover:to-teal-700 text-white font-black text-base tracking-wider px-8 py-4 rounded-2xl shadow-[0_0_25px_rgba(16,185,129,0.4)] hover:scale-105 active:scale-95 transition-all duration-300 border border-white/15">
                        <span>LƯU ĐIỂM & TIẾP TỤC</span> <i class="fas fa-arrow-right"></i>
                    </button>
                </div>
            </div>

            <!-- BOTTOM AREA: Player & Progress -->
            <div class="bg-slate-50 px-8 py-5 border-t-4 border-slate-200 flex flex-wrap items-center justify-between gap-6 z-10">
                <!-- Replay & Audio Controls -->
                <div class="flex items-center gap-4">
                    <button type="button" 
                            id="btn-sound-play" 
                            class="w-14 h-14 rounded-full bg-gradient-to-r from-indigo-500 to-purple-600 text-white flex items-center justify-center shadow-lg hover:scale-105 active:scale-95 transition-all duration-300 cursor-pointer border border-white/20 disabled:opacity-50"
                            disabled>
                        <i class="fas fa-volume-up text-xl"></i>
                    </button>
                    <div>
                        <span class="text-[9px] font-black text-slate-400 uppercase tracking-widest block font-mono">BÀI NGHE PHÁT TỰ ĐỘNG</span>
                        <span class="text-xs font-bold text-slate-600" id="audio-status-text">Đang chuẩn bị...</span>
                    </div>
                </div>

                <!-- Progress Bar -->
                <div class="flex-grow max-w-xl flex items-center gap-3">
                    <span class="text-xs font-mono font-black text-slate-500 min-w-[70px] text-right" id="progress-text">CÂU 1/1</span>
                    <div class="flex-grow bg-slate-200 h-4 rounded-full p-0.5 border border-slate-300 overflow-hidden shadow-inner">
                        <div id="hud-progress-bar" class="bg-gradient-to-r from-sky-400 via-blue-500 to-indigo-500 h-full w-0 rounded-full transition-all duration-300 relative">
                            <span class="absolute top-0.5 inset-x-0 h-0.5 bg-white/20 rounded-full"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- RIGHT PANEL (Mission & Collection) -->
        <div class="w-full lg:w-80 shrink-0 flex flex-col gap-6 select-none">
            <!-- Mission Card -->
            <div class="bg-white border-4 border-amber-300 rounded-[2rem] p-5 shadow-lg flex flex-col gap-3 relative overflow-hidden">
                <div class="absolute -right-4 -top-4 w-12 h-12 bg-amber-100 rounded-full opacity-40 pointer-events-none"></div>
                <div class="border-b border-slate-100 pb-2 flex items-center gap-2">
                    <span class="text-lg">🎯</span>
                    <h5 class="font-black text-slate-800 tracking-wide uppercase text-xs mb-0 font-mono">NHIỆM VỤ CỬA ẢI</h5>
                </div>
                <div class="text-[11px] text-slate-600 space-y-2 leading-relaxed">
                    <p class="font-bold flex items-start gap-1.5"><span class="text-sky-500">❶</span> Lắng nghe tệp âm thanh được phát.</p>
                    <p class="font-bold flex items-start gap-1.5"><span class="text-sky-500">❷</span> Nhấp vào con cá mang từ/câu nghe được.</p>
                    <p class="font-bold flex items-start gap-1.5"><span class="text-sky-500">❸</span> Trực giác quyết định: Bắt giữ <span class="text-amber-500 font-extrabold">[BẮT GIỮ]</span> (đáp án đúng) hoặc Thả ra <span class="text-slate-500 font-extrabold">[THẢ RA]</span> (đáp án sai).</p>
                </div>
            </div>

            <!-- Collection Card -->
            <div class="bg-white border-4 border-amber-300 rounded-[2rem] p-5 shadow-lg flex-grow flex flex-col gap-3 relative overflow-hidden">
                <div class="absolute -right-4 -bottom-4 w-16 h-16 bg-blue-50 rounded-full opacity-40 pointer-events-none"></div>
                <div class="border-b border-slate-100 pb-2 flex items-center justify-between">
                    <div class="flex items-center gap-2">
                        <span class="text-lg">🐠</span>
                        <h5 class="font-black text-slate-800 tracking-wide uppercase text-xs mb-0 font-mono">BỘ SƯU TẬP CÁ</h5>
                    </div>
                    <span class="text-[10px] font-mono font-black text-amber-500 bg-amber-100 px-2 py-0.5 rounded-full" id="collection-count">0/9 Unlocked</span>
                </div>
                <!-- Grid of collected fish -->
                <div class="grid grid-cols-3 gap-3 overflow-y-auto max-h-[300px] pr-1 custom-scrollbar" id="collection-grid">
                    <!-- Fish items will be added here dynamically -->
                </div>
            </div>
        </div>

    </div>
</div>

<!-- CATCH CONFIRMATION POPUP MODAL -->
<div id="catch-confirm-modal" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm hidden select-none">
    <div class="bg-white border-8 border-amber-300 rounded-[3rem] w-full max-w-sm p-6 text-center shadow-[0_20px_50px_rgba(0,0,0,0.3)] relative overflow-hidden transform scale-95 opacity-0 transition-all duration-300" id="catch-confirm-box">
        <!-- Sunburst glow behind fish -->
        <div class="absolute -top-12 inset-x-0 h-44 bg-gradient-to-b from-amber-200/40 to-transparent rounded-full filter blur-xl pointer-events-none"></div>
        
        <h3 class="text-2xl font-black text-slate-800 uppercase tracking-wide mb-1" style="font-family: 'Outfit', sans-serif;">CÁ ĐÃ CẮN CÂU!</h3>
        <p class="text-[10px] text-slate-400 mb-4 font-mono uppercase tracking-widest font-bold">Xác nhận để kéo lên tàu</p>

        <!-- Fish Display Card -->
        <div class="bg-sky-50 border-4 border-sky-100 rounded-3xl p-6 mb-6 relative flex flex-col items-center justify-center overflow-hidden shadow-inner">
            <!-- Fish Image inside dialog -->
            <div class="w-28 h-28 flex items-center justify-center mb-3 animate-bounce" style="animation-duration: 2s;">
                <img id="caught-fish-img" src="" class="w-full h-full object-contain" />
            </div>
            <!-- Answer Label -->
            <div class="bg-blue-600 text-white font-black text-sm px-6 py-2 rounded-full uppercase tracking-wider shadow-md border-2 border-white" id="caught-fish-label">
                COFFEE
            </div>
        </div>

        <!-- Confirm buttons -->
        <div class="flex gap-3 relative z-10">
            <button type="button" id="btn-release-fish" class="flex-1 py-3.5 rounded-2xl bg-slate-100 hover:bg-slate-200 text-slate-600 font-extrabold tracking-wider shadow-md active:translate-y-[2px] transition-all cursor-pointer text-xs uppercase border border-slate-200">
                Thả Ra (Release)
            </button>
            <button type="button" id="btn-keep-fish" class="flex-1 py-3.5 rounded-2xl bg-gradient-to-r from-amber-400 to-orange-500 hover:from-amber-300 hover:to-orange-400 text-slate-950 font-black tracking-wider shadow-lg active:translate-y-[2px] transition-all cursor-pointer text-xs uppercase border border-amber-300/30">
                Bắt Giữ (Keep)
            </button>
        </div>
    </div>
</div>

<!-- HIDDEN BACKEND POST FORM -->
<form action="{{ route('user.games.submit', $map->MaBanDo) }}" method="POST" id="catch-word-form" class="hidden">
    @csrf
    <input type="hidden" name="test_id" value="{{ $test->MaBai }}">
    <input type="hidden" name="start_time" value="{{ time() }}">
    
    @foreach($questions as $qIdx => $qData)
        <input type="hidden" name="answers[{{ $qData['question']->MaCauHoi }}]" id="ans-{{ $qData['question']->MaCauHoi }}" value="">
    @endforeach
</form>

<!-- CUSTOM STYLES -->
<style>
    /* Cozy animal-crossing styles override */
    #game-workspace {
        font-family: 'Outfit', system-ui, -apple-system, sans-serif;
    }

    /* Wave animations in background */
    @keyframes wave-move {
        0% { background-position-x: 0px; }
        100% { background-position-x: 1200px; }
    }
    .animate-wave-slow {
        animation: wave-move 12s linear infinite;
    }
    .animate-wave-fast {
        animation: wave-move 7s linear infinite;
    }

    /* Swimming fish styles */
    .fish-swimmer {
        position: absolute;
        width: 84px;
        height: 84px;
        cursor: pointer;
        will-change: left, top;
        transition: transform 0.2s ease, opacity 0.3s ease;
        z-index: 12;
    }
    .fish-swimmer img {
        width: 100%;
        height: 100%;
        object-fit: contain;
    }
    .fish-sprite-wrapper {
        width: 100%;
        height: 100%;
        animation: swim-wiggle 1s ease-in-out infinite alternate;
    }
    
    @keyframes swim-wiggle {
        0% { transform: rotate(-5deg); }
        100% { transform: rotate(5deg); }
    }

    .fish-swimmer:hover {
        scale: 1.12;
        filter: drop-shadow(0 0 10px rgba(34, 211, 238, 0.6));
    }

    /* Text bubbles above swimming fish heads */
    .fish-bubble-label {
        position: absolute;
        bottom: 90%;
        left: 50%;
        transform: translateX(-50%);
        background: rgba(255, 255, 255, 0.95);
        color: #0f172a;
        font-weight: 800;
        font-size: 10px;
        padding: 4px 10px;
        border-radius: 9999px;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15), inset 0 0 0 1px rgba(0, 0, 0, 0.05);
        white-space: nowrap;
        pointer-events: none;
        letter-spacing: 0.02em;
        text-transform: uppercase;
        border: 2px solid #38bdf8;
        z-index: 15;
    }
    .fish-bubble-label::after {
        content: '';
        position: absolute;
        top: 100%;
        left: 50%;
        transform: translateX(-50%);
        border: 5px solid transparent;
        border-top-color: #38bdf8;
    }

    /* Floating feedback score bubbles */
    .score-indicator-popup {
        position: absolute;
        font-weight: 900;
        font-size: 24px;
        color: #fbbf24;
        text-shadow: 0 2px 4px rgba(0, 0, 0, 0.5), 0 0 10px rgba(251, 191, 36, 0.6);
        pointer-events: none;
        z-index: 45;
        animation: float-up-fade 1.2s cubic-bezier(0.18, 0.89, 0.32, 1.28) forwards;
    }
    @keyframes float-up-fade {
        0% { transform: translateY(20px) scale(0.6); opacity: 0; }
        20% { transform: translateY(0) scale(1.2); opacity: 1; }
        100% { transform: translateY(-70px) scale(0.9); opacity: 0; }
    }

    /* Unlocked fish slots */
    .collection-slot {
        background-color: #f1f5f9;
        border: 3px solid #e2e8f0;
        border-radius: 1.25rem;
        aspect-ratio: 1;
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative;
        transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    }
    .collection-slot.locked img {
        filter: grayscale(1) opacity(0.25);
    }
    .collection-slot.unlocked {
        background-color: #f0fdf4;
        border-color: #86efac;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
    }
    .collection-slot.unlocked img {
        filter: none;
        animation: slot-bounce 0.6s ease-out;
    }
    @keyframes slot-bounce {
        0%, 100% { transform: scale(1); }
        50% { transform: scale(1.25) rotate(5deg); }
    }

    /* Particles generic setup */
    .game-particle {
        position: absolute;
        pointer-events: none;
        border-radius: 50%;
        will-change: transform, opacity;
    }
</style>

<!-- GAME LOGIC SCRIPT -->
<script>
document.addEventListener('DOMContentLoaded', () => {
    // 1. Data Loader from PHP Blade
    const questionsData = [
        @foreach($questions as $qIdx => $qData)
            {
                id: "{{ $qData['question']->MaCauHoi }}",
                audioUrl: "{{ $qData['audio'] }}",
                correctOptionId: "{{ $qData['correct_option'] ? $qData['correct_option']->MaPA : '' }}",
                correctText: "{{ $qData['correct_option'] ? preg_replace('/^[A-D]\.\s*/', '', $qData['correct_option']->NDPA) : '' }}",
                options: [
                    @foreach($qData['options'] as $opt)
                        {
                            id: "{{ $opt->MaPA }}",
                            text: "{{ preg_replace('/^[A-D]\.\s*/', '', $opt->NDPA) }}",
                            isCorrect: {{ $opt->DapAn === 'Dung' ? 'true' : 'false' }}
                        },
                    @endforeach
                ]
            },
        @endforeach
    ];

    // Web Audio Synthesizer for Cozy sound effects
    let audioCtx = null;
    const initAudioContext = () => {
        if (!audioCtx) {
            audioCtx = new (window.AudioContext || window.webkitAudioContext)();
        }
        if (audioCtx.state === 'suspended') {
            audioCtx.resume();
        }
    };

    const synthBeep = (freq, duration, type = 'sine', decay = true) => {
        if (!audioCtx) return;
        try {
            const osc = audioCtx.createOscillator();
            const gain = audioCtx.createGain();
            osc.connect(gain);
            gain.connect(audioCtx.destination);
            
            osc.type = type;
            osc.frequency.setValueAtTime(freq, audioCtx.currentTime);
            
            gain.gain.setValueAtTime(0.08, audioCtx.currentTime);
            if (decay) {
                gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + duration);
            }
            
            osc.start();
            osc.stop(audioCtx.currentTime + duration);
        } catch(e) {}
    };

    const playCorrectSound = () => {
        synthBeep(440, 0.1, 'sine'); // A4
        setTimeout(() => synthBeep(554.37, 0.1, 'sine'), 80); // C#5
        setTimeout(() => synthBeep(659.25, 0.25, 'sine'), 160); // E5
    };

    const playWrongSound = () => {
        synthBeep(220, 0.15, 'triangle');
        setTimeout(() => synthBeep(180, 0.25, 'triangle'), 120);
    };

    const playWaterSplashSound = () => {
        if (!audioCtx) return;
        try {
            const bufferSize = audioCtx.sampleRate * 0.3; // 0.3 seconds
            const buffer = audioCtx.createBuffer(1, bufferSize, audioCtx.sampleRate);
            const data = buffer.getChannelData(0);
            for (let i = 0; i < bufferSize; i++) {
                data[i] = Math.random() * 2 - 1;
            }
            const noise = audioCtx.createBufferSource();
            noise.buffer = buffer;

            const filter = audioCtx.createBiquadFilter();
            filter.type = 'bandpass';
            filter.frequency.setValueAtTime(1000, audioCtx.currentTime);
            filter.frequency.exponentialRampToValueAtTime(150, audioCtx.currentTime + 0.3);

            const gain = audioCtx.createGain();
            gain.gain.setValueAtTime(0.05, audioCtx.currentTime);
            gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.3);

            noise.connect(filter);
            filter.connect(gain);
            gain.connect(audioCtx.destination);
            noise.start();
        } catch (e) {}
    };

    // HTML Elements References
    const screenLaunch = document.getElementById('screen-launch');
    const screenGameOver = document.getElementById('screen-gameover');
    const screenWin = document.getElementById('screen-win');
    const swimmingZone = document.getElementById('swimming-zone');
    const btnStart = document.getElementById('btn-game-start');
    const btnReplay = document.getElementById('btn-game-replay');
    const btnSubmit = document.getElementById('btn-submit-game');
    const btnSoundPlay = document.getElementById('btn-sound-play');
    const heartsContainer = document.getElementById('hearts-container');
    const xpDisplay = document.getElementById('xp-display');
    const coinsDisplay = document.getElementById('coins-display');
    const comboDisplay = document.getElementById('combo-display');
    const comboHudWrapper = document.getElementById('combo-hud-wrapper');
    const progressText = document.getElementById('progress-text');
    const hudProgressBar = document.getElementById('hud-progress-bar');
    const audioStatusText = document.getElementById('audio-status-text');
    const gameModeBadge = document.getElementById('game-mode-badge');
    const collectionCount = document.getElementById('collection-count');
    const collectionGrid = document.getElementById('collection-grid');
    const oceanScene = document.getElementById('ocean-scene');
    const fisherman = document.getElementById('fisherman-character');
    
    // Catch Confirm Modal References
    const catchConfirmModal = document.getElementById('catch-confirm-modal');
    const catchConfirmBox = document.getElementById('catch-confirm-box');
    const caughtFishImg = document.getElementById('caught-fish-img');
    const caughtFishLabel = document.getElementById('caught-fish-label');
    const btnKeepFish = document.getElementById('btn-keep-fish');
    const btnReleaseFish = document.getElementById('btn-release-fish');

    // Game State variables
    let activeQuestionIndex = 0;
    let score = 0; // represent XP
    let coins = 0;
    let lives = 3;
    let combo = 0;
    let isGameRunning = false;
    let targetWordAudio = new Audio();
    let fishList = []; // Swimming fish instances
    let loopAnimId = null;
    let unlockedFish = Array(10).fill(false); // 9 fish characters (1-indexed)
    let selectedFishObject = null; // Fish currently caught/clicked

    // Boat and hook variables
    let boatX = 10;
    let boatDir = 1; // 1 = right, -1 = left
    const boatSpeed = 1.8;
    let hookState = 'idle'; // 'idle', 'descending', 'ascending'
    let hookX = 0;
    let hookY = 0;
    const hookSpeed = 6;
    let caughtFish = null;

    // Initialize the fish collection layout on the right
    const initCollectionUI = () => {
        collectionGrid.innerHTML = '';
        for (let i = 1; i <= 9; i++) {
            const slot = document.createElement('div');
            slot.className = `collection-slot locked` ;
            slot.id = `col-slot-${i}`;
            
            const img = document.createElement('img');
            img.src = `{{ asset('images/fishing/fish_') }}${i}.png`;
            img.className = 'w-10 h-10 object-contain';
            
            slot.appendChild(img);
            collectionGrid.appendChild(slot);
        }
    };

    const updateCollectionCount = () => {
        const count = unlockedFish.filter(v => v).length;
        collectionCount.innerText = `${count}/9 Unlocked`;
    };

    const unlockFishInUI = (fishIdx) => {
        if (fishIdx < 1 || fishIdx > 9) return;
        unlockedFish[fishIdx] = true;
        const slot = document.getElementById(`col-slot-${fishIdx}`);
        if (slot) {
            slot.classList.remove('locked');
            slot.classList.add('unlocked');
        }
        updateCollectionCount();
    };

    // Render hearts in HUD
    const renderHearts = () => {
        let heartsHtml = '';
        for (let i = 0; i < 3; i++) {
            if (i < lives) {
                heartsHtml += '❤️';
            } else {
                heartsHtml += '🖤';
            }
        }
        heartsContainer.innerHTML = heartsHtml;
    };

    // Detect game mode based on text length
    const detectMode = (text) => {
        const clean = text.trim();
        const wordCount = clean.split(/\s+/).length;
        if (clean.includes(':') || clean.includes('?') && clean.includes('A:')) {
            return "Dialogue Listening";
        } else if (wordCount === 1) {
            return "Word Listening";
        } else if (wordCount <= 4) {
            return "Phrase Listening";
        } else {
            return "Sentence Listening";
        }
    };

    // Play current question's audio
    const playCurrentAudio = () => {
        const currentQ = questionsData[activeQuestionIndex];
        if (currentQ && currentQ.audioUrl) {
            targetWordAudio.src = currentQ.audioUrl;
            audioStatusText.innerText = 'Đang phát âm thanh...';
            btnSoundPlay.classList.add('animate-pulse');
            
            targetWordAudio.play().catch(e => {
                console.log('Autoplay blocked by browser');
                audioStatusText.innerText = 'Nhấp LOA để nghe';
                btnSoundPlay.classList.remove('animate-pulse');
            });
        } else {
            audioStatusText.innerText = 'Không có âm thanh';
        }
    };

    targetWordAudio.addEventListener('ended', () => {
        audioStatusText.innerText = 'Nghe lại (Replay)';
        btnSoundPlay.classList.remove('animate-pulse');
    });

    btnSoundPlay.addEventListener('click', (e) => {
        e.stopPropagation();
        initAudioContext();
        playCurrentAudio();
    });

    // Update HUD Stats
    const updateHUD = () => {
        const total = questionsData.length;
        progressText.innerText = `CÂU ${activeQuestionIndex + 1}/${total}`;
        
        const pct = (activeQuestionIndex / total) * 100;
        hudProgressBar.style.width = `${pct}%`;
        
        xpDisplay.innerText = `${score} XP`;
        coinsDisplay.innerText = `${coins}`;
        
        const multiplier = (1.0 + combo * 0.1).toFixed(1);
        comboDisplay.innerText = `${multiplier}x`;
        if (combo > 0) {
            comboHudWrapper.classList.add('animate-pulse', 'border-orange-500/80');
            comboHudWrapper.classList.remove('border-orange-400/30');
        } else {
            comboHudWrapper.classList.remove('animate-pulse', 'border-orange-500/80');
            comboHudWrapper.classList.add('border-orange-400/30');
        }

        // Detect and set active mode badge
        const currentQ = questionsData[activeQuestionIndex];
        if (currentQ) {
            gameModeBadge.innerText = detectMode(currentQ.correctText);
        }
    };

    // Calculate rod tip coordinates dynamically based on fisherman position
    const getRodTip = () => {
        const oceanRect = oceanScene.getBoundingClientRect();
        const fisherRect = fisherman.getBoundingClientRect();
        
        const isFlipped = fisherman.style.transform.includes('scaleX(-1)');
        const ratioX = isFlipped ? 0.835 : 0.165;
        
        const x = (fisherRect.left - oceanRect.left) + fisherRect.width * ratioX;
        const y = (fisherRect.top - oceanRect.top) + fisherRect.height * 0.22;
        return { x, y };
    };

    // Particle effect creator
    const spawnParticles = (x, y, colors, isSplash = false) => {
        const count = 16;
        for (let i = 0; i < count; i++) {
            const p = document.createElement('div');
            p.className = 'game-particle shadow-sm';
            p.style.left = `${x}px`;
            p.style.top = `${y}px`;
            
            const size = isSplash ? (4 + Math.random() * 8) : (6 + Math.random() * 8);
            p.style.width = `${size}px`;
            p.style.height = `${size}px`;
            p.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
            
            if (isSplash) {
                // teardrop shape
                p.style.borderRadius = '50% 50% 50% 50% / 60% 60% 40% 40%';
            }
            
            oceanScene.appendChild(p);
            
            // splash goes up and out, sparkle goes all directions
            const angle = isSplash ? (-Math.PI / 2 + (Math.random() - 0.5) * 0.9) : (Math.random() * Math.PI * 2);
            const speed = isSplash ? (3 + Math.random() * 6) : (2 + Math.random() * 4);
            let vx = Math.cos(angle) * speed;
            let vy = Math.sin(angle) * speed;
            
            let alpha = 1;
            let px = x;
            let py = y;
            
            const update = () => {
                px += vx;
                py += vy;
                if (isSplash) {
                    vy += 0.22; // gravity
                }
                alpha -= 0.025;
                
                p.style.transform = `translate(${px - x}px, ${py - y}px) scale(${alpha})`;
                p.style.opacity = alpha;
                
                if (alpha > 0) {
                    requestAnimationFrame(update);
                } else {
                    p.remove();
                }
            };
            requestAnimationFrame(update);
        }
    };

    // Text popups (floating damage-style numbers)
    const floatText = (x, y, text, colorClass = 'text-amber-400') => {
        const el = document.createElement('div');
        el.className = `score-indicator-popup ${colorClass}`;
        el.innerText = text;
        el.style.left = `${x}px`;
        el.style.top = `${y}px`;
        
        oceanScene.appendChild(el);
        setTimeout(() => el.remove(), 1200);
    };

    // Fish spawning logic
    const spawnSwimmingFish = () => {
        // Clear old fish
        swimmingZone.innerHTML = '';
        fishList = [];

        // Pool all options of all questions
        const allOptions = [];
        questionsData.forEach((qData) => {
            qData.options.forEach((opt) => {
                allOptions.push({
                    opt: opt,
                    questionId: qData.id
                });
            });
        });

        if (allOptions.length === 0) return;

        const oceanW = oceanScene.clientWidth;

        allOptions.forEach((item, idx) => {
            const opt = item.opt;
            const fishDiv = document.createElement('div');
            fishDiv.className = 'fish-swimmer';
            
            const spriteWrapper = document.createElement('div');
            spriteWrapper.className = 'fish-sprite-wrapper';

            // Alternating yellow and blue fish images
            const isYellow = (idx % 2 === 0);
            const fishSrc = isYellow ? "{{ asset('images/fishing/map2_fish_yellow.png') }}" : "{{ asset('images/fishing/map2_fish_blue.jpg') }}";
            
            const fishImg = document.createElement('img');
            fishImg.src = fishSrc;
            
            const label = document.createElement('span');
            label.className = 'fish-bubble-label';
            label.innerText = opt.text;
            
            spriteWrapper.appendChild(fishImg);
            fishDiv.appendChild(spriteWrapper);
            fishDiv.appendChild(label);
            swimmingZone.appendChild(fishDiv);

            // Starting position (distributed across grid columns)
            const gridX = (oceanW / (allOptions.length + 1)) * (idx + 1);
            // vertical swim zone between 240px and 430px (bottom)
            const randomY = 240 + Math.random() * 160; 

            // velocity
            const direction = Math.random() > 0.5 ? 1 : -1;
            const speed = 0.6 + Math.random() * 0.7;
            const vx = direction * speed;

            fishDiv.style.left = `${gridX}px`;
            fishDiv.style.top = `${randomY}px`;
            fishImg.style.transform = vx > 0 ? 'scaleX(-1)' : 'scaleX(1)';

            const fishObj = {
                element: fishDiv,
                questionId: item.questionId,
                optionId: opt.id,
                text: opt.text,
                isCorrect: opt.isCorrect,
                imageSrc: fishSrc,
                spriteIdx: (idx % 9) + 1,
                x: gridX,
                y: randomY,
                vx: vx,
                speed: speed,
                randomOffset: Math.random() * 100,
                isHooked: false
            };

            fishList.push(fishObj);
        });
    };

    const restoreFishSpeeds = () => {
        fishList.forEach(f => {
            if (!f.isHooked) {
                f.vx = Math.sign(f.vx) * f.speed;
            }
        });
    };

    // Fish jumps upward parabolic arc, then triggers popup modal
    const jumpFishUpward = (fish) => {
        const tip = getRodTip();
        const targetX = oceanScene.clientWidth / 2;
        const targetY = oceanScene.clientHeight / 2 - 40;

        const duration = 650; // ms
        const startTime = performance.now();

        const jumpEl = document.createElement('img');
        jumpEl.src = fish.imageSrc;
        jumpEl.className = 'absolute w-20 h-20 z-40 pointer-events-none';
        jumpEl.style.left = `${tip.x}px`;
        jumpEl.style.top = `${tip.y}px`;
        oceanScene.appendChild(jumpEl);

        const animateJump = (time) => {
            const elapsed = time - startTime;
            const t = Math.min(elapsed / duration, 1);

            // X coordinates linear interpolation
            const curX = tip.x + (targetX - tip.x) * t - 40;
            // Y coordinates parabolic trajectory
            const peak = 120; // max jump height pixels
            const curY = tip.y + (targetY - tip.y) * t - 40 - peak * Math.sin(Math.PI * t);

            jumpEl.style.left = `${curX}px`;
            jumpEl.style.top = `${curY}px`;
            // Spin the fish as it flies
            jumpEl.style.transform = `rotate(${t * 360}deg) scale(${1 + 0.3 * Math.sin(Math.PI * t)})`;

            if (t < 1) {
                requestAnimationFrame(animateJump);
            } else {
                jumpEl.remove();
                selectedFishObject = fish;
                showCatchConfirmModal(fish);
            }
        };

        requestAnimationFrame(animateJump);
    };

    // Show Confirmation popup Modal
    const showCatchConfirmModal = (fish) => {
        caughtFishImg.src = fish.imageSrc;
        caughtFishLabel.innerText = fish.text;

        catchConfirmModal.classList.remove('hidden');
        // Trigger scale pop animation
        setTimeout(() => {
            catchConfirmBox.classList.remove('scale-95', 'opacity-0');
            catchConfirmBox.classList.add('scale-100', 'opacity-100');
        }, 50);
    };

    const hideCatchConfirmModal = () => {
        catchConfirmBox.classList.remove('scale-100', 'opacity-100');
        catchConfirmBox.classList.add('scale-95', 'opacity-0');
        setTimeout(() => {
            catchConfirmModal.classList.add('hidden');
        }, 300);
    };

    // Decision checking: Keep fish clicked
    btnKeepFish.addEventListener('click', (e) => {
        e.stopPropagation();
        if (!selectedFishObject) return;
        hideCatchConfirmModal();

        const fish = selectedFishObject;
        const screenMidX = oceanScene.clientWidth / 2;
        const screenMidY = oceanScene.clientHeight / 2;
        const currentQ = questionsData[activeQuestionIndex];
        const isCorrect = (fish.optionId === currentQ.correctOptionId);

        if (isCorrect) {
            // Write answer choice to input
            const hiddenInp = document.getElementById('ans-' + currentQ.id);
            if (hiddenInp) {
                hiddenInp.value = fish.optionId;
            }

            // Streak updates
            combo++;
            score += Math.round(100 * (1.0 + combo * 0.1));
            coins += 10;

            // Success feedback
            playCorrectSound();
            spawnParticles(screenMidX, screenMidY, ['#fbbf24', '#f59e0b', '#fb7185', '#fef08a'], false);
            floatText(screenMidX - 40, screenMidY - 30, `+100 XP`, 'text-emerald-500');
            
            // Add fish to collection
            unlockFishInUI(fish.spriteIdx);

            // Advance to next question
            activeQuestionIndex++;
            updateHUD();

            setTimeout(() => {
                if (activeQuestionIndex >= questionsData.length) {
                    endGame(true);
                } else {
                    // Just play next audio, fish remains hidden (captured)
                    restoreFishSpeeds();
                    playCurrentAudio();
                }
            }, 1000);

        } else {
            // Incorrect Keep decision: Lose life
            lives--;
            combo = 0;
            playWrongSound();
            spawnParticles(screenMidX, screenMidY, ['#f43f5e', '#ef4444', '#fda4af', '#cbd5e1'], true);
            floatText(screenMidX - 40, screenMidY - 30, `-1 LIFE`, 'text-rose-500');
            renderHearts();
            updateHUD();

            // Subtle shake on ocean screen container
            oceanScene.parentElement.classList.add('animate-shake');
            setTimeout(() => oceanScene.parentElement.classList.remove('animate-shake'), 350);

            setTimeout(() => {
                if (lives <= 0) {
                    endGame(false);
                } else {
                    // Release the fish back into the water
                    fish.isHooked = false;
                    fish.element.classList.remove('hidden');
                    fish.x = 50 + Math.random() * (oceanScene.clientWidth - 150);
                    fish.y = 240 + Math.random() * 160;
                    fish.element.style.left = `${fish.x}px`;
                    fish.element.style.top = `${fish.y}px`;
                    
                    const direction = Math.random() > 0.5 ? 1 : -1;
                    fish.vx = direction * (0.6 + Math.random() * 0.7);
                    fish.speed = Math.abs(fish.vx);
                    
                    const img = fish.element.querySelector('img');
                    if (img) img.style.transform = fish.vx > 0 ? 'scaleX(-1)' : 'scaleX(1)';

                    restoreFishSpeeds();
                    playCurrentAudio();
                }
            }, 1000);
        }

        selectedFishObject = null;
    });

    // Decision checking: Release fish clicked
    btnReleaseFish.addEventListener('click', (e) => {
        e.stopPropagation();
        if (!selectedFishObject) return;
        hideCatchConfirmModal();

        const fish = selectedFishObject;
        const screenMidX = oceanScene.clientWidth / 2;
        const screenMidY = oceanScene.clientHeight / 2;
        const currentQ = questionsData[activeQuestionIndex];
        const isCorrect = (fish.optionId === currentQ.correctOptionId);

        if (!isCorrect) {
            // Correct Release decision: No penalty, continue fishing
            playCorrectSound();
            floatText(screenMidX - 60, screenMidY - 30, `AN TOÀN!`, 'text-sky-500');
            
            // Drop fish back into water
            spawnParticles(screenMidX, screenMidY, ['#38bdf8', '#bae6fd', '#e2e8f0'], true);

            setTimeout(() => {
                // Release the fish back into the water
                fish.isHooked = false;
                fish.element.classList.remove('hidden');
                fish.x = 50 + Math.random() * (oceanScene.clientWidth - 150);
                fish.y = 240 + Math.random() * 160;
                fish.element.style.left = `${fish.x}px`;
                fish.element.style.top = `${fish.y}px`;
                
                const direction = Math.random() > 0.5 ? 1 : -1;
                fish.vx = direction * (0.6 + Math.random() * 0.7);
                fish.speed = Math.abs(fish.vx);
                
                const img = fish.element.querySelector('img');
                if (img) img.style.transform = fish.vx > 0 ? 'scaleX(-1)' : 'scaleX(1)';

                restoreFishSpeeds();
                playCurrentAudio();
            }, 1000);

        } else {
            // Incorrect Release decision: Lose opportunity (Lose 1 life)
            lives--;
            combo = 0;
            playWrongSound();
            spawnParticles(screenMidX, screenMidY, ['#f43f5e', '#ef4444', '#fda4af'], true);
            floatText(screenMidX - 60, screenMidY - 30, `BỎ LỠ CƠ HỘI!`, 'text-orange-500');
            renderHearts();
            updateHUD();

            // Screen shake
            oceanScene.parentElement.classList.add('animate-shake');
            setTimeout(() => oceanScene.parentElement.classList.remove('animate-shake'), 350);

            setTimeout(() => {
                if (lives <= 0) {
                    endGame(false);
                } else {
                    // Release the fish back into the water
                    fish.isHooked = false;
                    fish.element.classList.remove('hidden');
                    fish.x = 50 + Math.random() * (oceanScene.clientWidth - 150);
                    fish.y = 240 + Math.random() * 160;
                    fish.element.style.left = `${fish.x}px`;
                    fish.element.style.top = `${fish.y}px`;
                    
                    const direction = Math.random() > 0.5 ? 1 : -1;
                    fish.vx = direction * (0.6 + Math.random() * 0.7);
                    fish.speed = Math.abs(fish.vx);
                    
                    const img = fish.element.querySelector('img');
                    if (img) img.style.transform = fish.vx > 0 ? 'scaleX(-1)' : 'scaleX(1)';

                    restoreFishSpeeds();
                    playCurrentAudio();
                }
            }, 1000);
        }

        selectedFishObject = null;
    });

    // Handle clicking anywhere in ocean scene to drop hook
    oceanScene.addEventListener('click', (e) => {
        if (!isGameRunning || hookState !== 'idle' || selectedFishObject) return;

        // Prevent casting if any screen or modal overlay is open
        const isModalOpen = !screenLaunch.classList.contains('hidden') || 
                            !screenGameOver.classList.contains('hidden') || 
                            !screenWin.classList.contains('hidden') || 
                            !catchConfirmModal.classList.contains('hidden');
        if (isModalOpen) return;

        initAudioContext();
        
        hookState = 'descending';
        const tip = getRodTip();
        hookX = tip.x;
        hookY = tip.y;
        
        const hookEl = document.getElementById('fishing-hook');
        if (hookEl) {
            hookEl.classList.remove('hidden');
            hookEl.style.left = `${hookX - 12}px`;
            hookEl.style.top = `${hookY}px`;
        }
        
        playWaterSplashSound();
    });

    // Main animation loop tick for boat moving and fish swimming
    const gameLoopTick = () => {
        if (!isGameRunning) return;

        const oceanW = oceanScene.clientWidth;
        const tip = getRodTip();

        // 1. Horizontal boat movement
        if (hookState === 'idle' && !selectedFishObject) {
            boatX += boatDir * boatSpeed;
            const boatWidth = 150;
            const minX = 10;
            const maxX = oceanW - boatWidth - 10;

            if (boatX > maxX) {
                boatX = maxX;
                boatDir = -1;
            } else if (boatX < minX) {
                boatX = minX;
                boatDir = 1;
            }

            fisherman.style.left = `${boatX}px`;
            fisherman.style.transform = boatDir > 0 ? 'scaleX(-1)' : 'scaleX(1)';
        }

        // 2. Hook state machine
        const linePath = document.getElementById('fishing-line-path');
        const hookEl = document.getElementById('fishing-hook');

        if (hookState === 'descending') {
            hookY += hookSpeed;

            // Draw line
            linePath.setAttribute('d', `M ${tip.x} ${tip.y} L ${hookX} ${hookY}`);

            // Update hook element position
            if (hookEl) {
                hookEl.style.left = `${hookX - 12}px`;
                hookEl.style.top = `${hookY}px`;
            }

            // Check collision with swimming fish
            for (let i = 0; i < fishList.length; i++) {
                const fish = fishList[i];
                if (!fish.isHooked) {
                    // Collision check (fish size is 84x84, hook hit zone adjusted for accuracy)
                    if (hookX >= fish.x - 5 && hookX <= fish.x + 89 && 
                        hookY >= fish.y - 5 && hookY <= fish.y + 89) {
                        fish.isHooked = true;
                        caughtFish = fish;
                        hookState = 'ascending';
                        playWaterSplashSound();

                        // Slow down other fish while reeling
                        fishList.forEach(f => {
                            if (f !== fish) {
                                f.vx = f.vx * 0.1;
                            }
                        });
                        break;
                    }
                }
            }

            // Reach bottom boundary
            if (hookY >= oceanScene.clientHeight - 40) {
                hookState = 'ascending';
            }
        } 
        else if (hookState === 'ascending') {
            hookY -= hookSpeed;

            // Draw line
            linePath.setAttribute('d', `M ${tip.x} ${tip.y} L ${hookX} ${hookY}`);

            // Update hook position
            if (hookEl) {
                hookEl.style.left = `${hookX - 12}px`;
                hookEl.style.top = `${hookY}px`;
            }

            // Drag caught fish along
            if (caughtFish) {
                caughtFish.x = hookX - 42;
                caughtFish.y = hookY - 20;
                caughtFish.element.style.left = `${caughtFish.x}px`;
                caughtFish.element.style.top = `${caughtFish.y}px`;
            }

            // Returned to rod tip
            if (hookY <= tip.y) {
                hookState = 'idle';
                if (hookEl) hookEl.classList.add('hidden');
                linePath.setAttribute('d', '');

                if (caughtFish) {
                    caughtFish.element.classList.add('hidden');
                    const fishToJump = caughtFish;
                    caughtFish = null;
                    jumpFishUpward(fishToJump);
                }
            }
        }

        // 3. Update swimming fish
        fishList.forEach(fish => {
            if (!fish.isHooked) {
                // Update position
                fish.x += fish.vx;
                fish.element.style.top = `${fish.y + Math.sin(Date.now() / 400 + fish.randomOffset) * 6}px`;
                fish.element.style.left = `${fish.x}px`;

                // Bounce off edges
                if (fish.vx > 0 && fish.x > oceanW - 90) {
                    fish.vx = -fish.vx;
                    const img = fish.element.querySelector('img');
                    if (img) img.style.transform = 'scaleX(1)';
                } else if (fish.vx < 0 && fish.x < 10) {
                    fish.vx = -fish.vx;
                    const img = fish.element.querySelector('img');
                    if (img) img.style.transform = 'scaleX(-1)';
                }
            }
        });

        loopAnimId = requestAnimationFrame(gameLoopTick);
    };

    // Start Game flow
    const startGame = () => {
        initAudioContext();
        screenLaunch.classList.add('hidden');
        screenGameOver.classList.add('hidden');
        screenWin.classList.add('hidden');
        
        btnSoundPlay.disabled = false;
        isGameRunning = true;

        // Reset boat and hook state variables
        boatX = 10;
        boatDir = 1;
        hookState = 'idle';
        caughtFish = null;
        selectedFishObject = null;

        const hookEl = document.getElementById('fishing-hook');
        if (hookEl) hookEl.classList.add('hidden');

        const linePath = document.getElementById('fishing-line-path');
        if (linePath) linePath.setAttribute('d', '');

        activeQuestionIndex = 0;
        score = 0;
        coins = 0;
        lives = 3;
        combo = 0;

        renderHearts();
        updateHUD();
        spawnSwimmingFish();
        playLaserSound();
        setTimeout(playCurrentAudio, 300);

        if (loopAnimId) {
            cancelAnimationFrame(loopAnimId);
        }
        loopAnimId = requestAnimationFrame(gameLoopTick);
    };

    // Laser sound effect helper
    const playLaserSound = () => {
        synthBeep(587.33, 0.1, 'sine'); // D5
    };

    // End Game (Win or Lose)
    const endGame = (isWin) => {
        isGameRunning = false;
        cancelAnimationFrame(loopAnimId);
        loopAnimId = null;
        btnSoundPlay.disabled = true;
        targetWordAudio.pause();

        const hookEl = document.getElementById('fishing-hook');
        if (hookEl) hookEl.classList.add('hidden');

        const linePath = document.getElementById('fishing-line-path');
        if (linePath) linePath.setAttribute('d', '');

        if (isWin) {
            hudProgressBar.style.width = '100%';
            screenWin.classList.remove('hidden');
            playCorrectSound();
        } else {
            screenGameOver.classList.remove('hidden');
        }
    };

    // Submit backend form
    btnSubmit.addEventListener('click', (e) => {
        e.stopPropagation();
        document.getElementById('catch-word-form').submit();
    });

    // Event listeners
    btnStart.addEventListener('click', (e) => {
        e.stopPropagation();
        startGame();
    });
    btnReplay.addEventListener('click', (e) => {
        e.stopPropagation();
        startGame();
    });

    // Initial setup calls
    initCollectionUI();
    updateCollectionCount();
});
</script>
